"""baseline schema

Revision ID: 9df78440fd86
Revises: 
Create Date: 2026-06-10 13:05:45.951446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df78440fd86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_path', sa.String(length=500), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s3_bucket', sa.String(length=200), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('item_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('apply_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('posted_date', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.String(length=50), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('score_strengths', sa.JSON(), nullable=True),
    sa.Column('score_concerns', sa.JSON(), nullable=True),
    sa.Column('score_recommendation', sa.String(length=50), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_score', 'jobs', ['score'], unique=False)
    op.create_index('idx_score_created', 'jobs', ['score', 'created_at'], unique=False)
    op.create_index('idx_score_recommendation', 'jobs', ['score_recommendation'], unique=False)
    op.create_index('idx_scored_at', 'jobs', ['scored_at'], unique=False)
    op.create_index('idx_source', 'jobs', ['source'], unique=False)
    op.create_index('idx_status', 'jobs', ['status'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_discovered', sa.Integer(), nullable=True),
    sa.Column('jobs_scored', sa.Integer(), nullable=True),
    sa.Column('jobs_enriched', sa.Integer(), nullable=True),
    sa.Column('applications_prepared', sa.Integer(), nullable=True),
    sa.Column('applications_submitted', sa.Integer(), nullable=True),
    sa.Column('applications_queued_for_review', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('niches', sa.JSON(), nullable=True),
    sa.Column('must_have_keywords', sa.JSON(), nullable=True),
    sa.Column('avoid_keywords', sa.JSON(), nullable=True),
    sa.Column('salary_floor', sa.Integer(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('remote_ok', sa.Boolean(), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('job_types', sa.JSON(), nullable=True),
    sa.Column('min_score_to_apply', sa.Integer(), nullable=True),
    sa.Column('auto_submit_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_application_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('run_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('input_config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('items_scraped', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_entries', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='fk_scraper_run_dataset', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actor_status', 'scraper_runs', ['actor_name', 'status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ats_platform', sa.String(length=50), nullable=True),
    sa.Column('ats_tracking_url', sa.String(length=1000), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('tailored_cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('automation_log', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_history', sa.JSON(), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tailored_cover_letter_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ats_platform_detected', sa.String(length=50), nullable=True),
    sa.Column('form_fields_detected', sa.Integer(), nullable=True),
    sa.Column('fields_filled', sa.Integer(), nullable=True),
    sa.Column('log_entries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_metrics')
    op.drop_table('applications')
    op.drop_index('idx_actor_status', table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_table('documents')
    op.drop_table('search_preferences')
    op.drop_table('profile')
    op.drop_table('pipeline_runs')
    op.drop_index('idx_status', table_name='jobs')
    op.drop_index('idx_source', table_name='jobs')
    op.drop_index('idx_scored_at', table_name='jobs')
    op.drop_index('idx_score_recommendation', table_name='jobs')
    op.drop_index('idx_score_created', table_name='jobs')
    op.drop_index('idx_score', table_name='jobs')
    op.drop_index('idx_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('datasets')
    op.drop_table('actors')
    # ### end Alembic commands ###
